"""Top-level package for docscriptor."""

from docscriptor.markup import md, markup
from docscriptor.model import (
    Body,
    BulletList,
    Chapter,
    Code,
    CodeBlock,
    Document,
    DocscriptorError,
    Emphasis,
    Figure,
    NumberedList,
    Paragraph,
    ParagraphStyle,
    Section,
    Strong,
    Subsection,
    Subsubsection,
    Table,
    Text,
    TextStyle,
    Theme,
    styled,
)

__version__ = "0.1.0"

__all__ = [
    "Body",
    "BulletList",
    "Chapter",
    "Code",
    "CodeBlock",
    "Document",
    "DocscriptorError",
    "Emphasis",
    "Figure",
    "NumberedList",
    "Paragraph",
    "ParagraphStyle",
    "Section",
    "Strong",
    "Subsection",
    "Subsubsection",
    "Table",
    "Text",
    "TextStyle",
    "Theme",
    "__version__",
    "md",
    "markup",
    "styled",
]
