"""Top-level package for docscriptor."""

from docscriptor.markup import md, markup
from docscriptor.model import (
    Body,
    Code,
    CodeBlock,
    Document,
    DocscriptorError,
    Emphasis,
    Figure,
    ListBlock,
    Paragraph,
    ParagraphStyle,
    Section,
    Strong,
    Subsection,
    Table,
    Text,
    TextStyle,
    Theme,
    body,
    bullet_list,
    code_block,
    document,
    figure,
    numbered_list,
    paragraph,
    section,
    styled,
    subsection,
    table,
)

__version__ = "0.1.0"

__all__ = [
    "Body",
    "Code",
    "CodeBlock",
    "Document",
    "DocscriptorError",
    "Emphasis",
    "Figure",
    "ListBlock",
    "Paragraph",
    "ParagraphStyle",
    "Section",
    "Strong",
    "Subsection",
    "Table",
    "Text",
    "TextStyle",
    "Theme",
    "__version__",
    "body",
    "bullet_list",
    "code_block",
    "document",
    "figure",
    "md",
    "markup",
    "numbered_list",
    "paragraph",
    "section",
    "styled",
    "subsection",
    "table",
]
